config-version: 1

# Root folder for database change scripts
root-folder: 'sql-scripts'

# Folder for jinja macros and templates (set to null if not used)
modules-folder: null

# Path to the dynamically created connections.toml file (in repo root)
connections-file-path: './connections.toml'

# Connection name from the TOML file
connection-name: {{ env_var('ENV') }}

# Change history table - environment variable can still be used
change-history-table: "DEMO_DB_{{ env_var('ENV') }}.SCHEMACHANGE.CHANGE_HISTORY"

# Define variables to use inside change scripts
vars:
  env: {{env_var('ENV') }}
  database: DEMO_DB_{{ env_var('ENV') }}

# Create change history table if not present
create-change-history-table: true

# Enable autocommit for DML commands
autocommit: false

# Enable verbose logging
verbose: true

# Run schemachange in actual mode (not dry-run)
dry-run: false

# Query tag for tracking
query-tag: 'QUERY_TAG'
