name: schemachange_dev
on:
  push:
    branches: [ "dev" ]
    
  workflow_dispatch:

jobs:
  deploy_Snowflake_Scripts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install schemachange
        run: pip install schemachange
          


